import { jsPDF } from "jspdf";
import { BookData } from "../types";

export const createBookPDF = (book: BookData): void => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // --- COVER PAGE ---
  
  // Background color for cover
  doc.setFillColor(30, 41, 59); // Slate 800
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Cover Image (if available)
  if (book.coverImageBase64) {
    try {
      const imgProps = doc.getImageProperties(`data:image/png;base64,${book.coverImageBase64}`);
      const imgRatio = imgProps.width / imgProps.height;
      
      // Calculate dimensions to fit nicely in the center
      const targetWidth = 120;
      const targetHeight = targetWidth / imgRatio;
      
      doc.addImage(
        `data:image/png;base64,${book.coverImageBase64}`,
        "PNG",
        (pageWidth - targetWidth) / 2,
        60,
        targetWidth,
        targetHeight
      );
    } catch (e) {
      console.warn("Could not add cover image to PDF", e);
    }
  }

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  
  const titleLines = doc.splitTextToSize(book.title, contentWidth);
  doc.text(titleLines, pageWidth / 2, pageHeight / 2 + 60, { align: "center" });

  // Subtitle / Topic
  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(200, 200, 200);
  doc.text(`A book about ${book.topic}`, pageWidth / 2, pageHeight - 30, { align: "center" });
  doc.text("Generated by AI BookSmith", pageWidth / 2, pageHeight - 20, { align: "center" });

  // --- CONTENT PAGES ---

  book.chapters.forEach((chapter, index) => {
    doc.addPage();
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, pageWidth, pageHeight, "F"); // White background
    doc.setTextColor(0, 0, 0);

    // Chapter Title
    doc.setFont("times", "bold");
    doc.setFontSize(22);
    doc.text(`Chapter ${index + 1}`, margin, 30);
    
    doc.setFontSize(18);
    doc.text(chapter.title, margin, 42);

    // Divider
    doc.setLineWidth(0.5);
    doc.line(margin, 50, pageWidth - margin, 50);

    // Chapter Content
    doc.setFont("times", "roman");
    doc.setFontSize(12);
    
    // Clean up markdown bold/italic markers roughly for PDF
    const cleanContent = (chapter.content || "")
      .replace(/\*\*/g, "") // Remove bold
      .replace(/\*/g, "")   // Remove italic
      .replace(/#/g, "");   // Remove headers

    const lines = doc.splitTextToSize(cleanContent, contentWidth);
    
    let y = 60;
    const lineHeight = 7;

    for (let i = 0; i < lines.length; i++) {
      if (y > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(lines[i], margin, y);
      y += lineHeight;
    }
    
    // Page number
    const pageNum = doc.getNumberOfPages();
    doc.setFontSize(10);
    doc.text(`${pageNum}`, pageWidth / 2, pageHeight - 10, { align: "center" });
  });

  doc.save(`${book.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
};
